// Englische Texte der WebUI, Schlüssel ist der deutsche Text (siehe i18n.ts).
// test/i18n.test.ts prüft, dass jeder t('…')-Schlüssel hier steht.
const en: Record<string, string> = {
  // Navigation, Rahmen
  'Start': 'Start',
  'Kalender': 'Calendar',
  'Aufgaben': 'Tasks',
  'Gewohnheiten': 'Habits',
  'Projekte': 'Projects',
  'Notizen': 'Notes',
  'Woche': 'Week',
  'Papierkorb': 'Trash',
  'Einstellungen': 'Settings',
  'Hauptnavigation': 'Main navigation',
  'Kairo': 'Kairo',
  'Neu': 'New',
  'Neu …': 'New …',
  'Verbunden': 'Connected',
  'Getrennt': 'Disconnected',
  'Theme wechseln': 'Toggle theme',
  'Seitenleiste ausklappen': 'Expand sidebar',
  'Seitenleiste einklappen': 'Collapse sidebar',
  'Ausklappen': 'Expand',
  'Einklappen': 'Collapse',
  'Aktiv': 'Active',
  'diese Woche': 'this week',

  // Allgemein
  'Abbrechen': 'Cancel',
  'Speichern': 'Save',
  'Anlegen': 'Create',
  'Löschen': 'Delete',
  'Löschen (⌫)': 'Delete (⌫)',
  'Endgültig löschen': 'Delete permanently',
  'Bearbeiten': 'Edit',
  'Schließen': 'Close',
  'Hinzufügen': 'Add',
  'Öffnen': 'Open',
  'Wählen': 'Choose',
  'Zurück': 'Back',
  'Zurück (←)': 'Back (←)',
  'Weiter': 'Next',
  'Weiter (→)': 'Next (→)',
  'Rückgängig': 'Undo',
  'Rückgängig (⌘Z)': 'Undo (⌘Z)',
  'Wiederholen': 'Redo',
  'Wiederholen (⇧⌘Z)': 'Redo (⇧⌘Z)',
  'Wiederherstellen': 'Restore',
  'Verschieben': 'Move',
  'Filter': 'Filter',
  'Alle': 'All',
  'Keine': 'None',
  'Name': 'Name',
  'Name (optional)': 'Name (optional)',
  'optional': 'optional',
  'Titel': 'Title',
  'Beschreibung': 'Description',
  'Status': 'Status',
  'Farbe': 'Color',
  'Ordner': 'Folder',
  'Ort': 'Location',
  'Datum': 'Date',
  'Uhrzeit': 'Time',
  'Von': 'From',
  'Bis': 'To',
  'bis': 'to',
  'Bis (einschließlich)': 'Until (inclusive)',
  'Ende': 'End',
  'Minuten': 'Minutes',
  'Std': 'h',
  'Min': 'min',
  'Lädt …': 'Loading …',
  'Suchen …': 'Search …',
  'Suchen (/)': 'Search (/)',
  'Gespeichert.': 'Saved.',
  'Ansicht': 'View',
  'Liste': 'List',
  'Kacheln': 'Tiles',
  'Tastenkürzel': 'Keyboard shortcuts',
  '…': '…',
  'API-Fehler': 'API error',
  'Backend nicht erreichbar.': 'Backend not reachable.',

  // Datum und Zeit
  'Heute': 'Today',
  'heute': 'today',
  'Heute (t)': 'Today (t)',
  'Morgen': 'Tomorrow',
  'Tag': 'Day',
  'Monat': 'Month',
  'KW': 'Wk',
  'Ganztag': 'All day',
  'Ganztags': 'All day',
  'Ganztägig': 'All day',
  'Diese Woche': 'This week',
  'Vorherige Woche': 'Previous week',
  'Nächste Woche': 'Next week',
  'Letzte 7 Tage': 'Last 7 days',
  '7 Tage': '7 days',
  'in {time}': 'in {time}',
  'seit {time}': 'since {time}',
  'danach': 'then',
  'Mo': 'Mon', 'Di': 'Tue', 'Mi': 'Wed', 'Do': 'Thu', 'Fr': 'Fri', 'Sa': 'Sat', 'So': 'Sun',
  'Sa/So': 'Sat/Sun',
  'Samstag und Sonntag anzeigen': 'Show Saturday and Sunday',

  // Aufgaben
  'Aufgabe': 'Task',
  'Task': 'Task',
  'Neue Aufgabe': 'New task',
  'Neue Aufgabe hinzufügen': 'Add new task',
  'Neue Aufgabe, z. B. Sport 30m @morgen #Kairo !hoch': 'New task, e.g. Gym 30m @tomorrow #Kairo !high',
  'Aufgabe hinzufügen, z. B. Sport 30m @morgen #Kairo': 'Add task, e.g. Gym 30m @tomorrow #Kairo',
  'Aufgabe für heute hinzufügen': 'Add task for today',
  '30m': '30m',
  '@datum': '@date',
  '#projekt': '#project',
  '!prio': '!prio',
  'Aufgaben durchsuchen': 'Search tasks',
  'Aufgabendetails': 'Task details',
  'Details schließen': 'Close details',
  'Aufgabe wählen': 'Choose task',
  'Alle Aufgaben': 'All tasks',
  'Offene Aufgaben': 'Open tasks',
  'Aufgaben dieser Woche': 'Tasks this week',
  'Offen': 'Open',
  'offen': 'open',
  'Erledigt': 'Done',
  'erledigt': 'done',
  'Abgebrochen': 'Cancelled',
  'Abgeschlossen': 'Completed',
  'Archiviert': 'Archived',
  'Pausiert': 'Paused',
  'Geplant': 'Planned',
  'geplant': 'planned',
  'Backlog': 'Backlog',
  'Läuft': 'Running',
  'läuft': 'running',
  'Pause': 'Pause',
  'Fertig': 'Done',
  'Fortsetzen': 'Resume',
  'Start/Pause': 'Start/Pause',
  'Jetzt starten': 'Start now',
  'Überfällig': 'Overdue',
  'überfällig': 'overdue',
  'Überfällig geworden': 'Became overdue',
  'Prio hoch': 'High priority',
  'eingeplant': 'scheduled',
  'nicht geplant': 'not planned',
  'Fällig': 'Due',
  'fällig': 'due',
  'Fälligkeit': 'due date',
  'Früher': 'Earlier',
  'Später': 'Later',
  'Ohne Datum': 'No date',
  'Ohne Projekt': 'No project',
  'Ohne Tag': 'No day',
  'Angelegt': 'Created',
  'Priorität': 'Priority',
  'Dringend': 'Urgent',
  'Hoch': 'High',
  'Mittel': 'Medium',
  'Niedrig': 'Low',
  'Projekt': 'Project',
  'Projekt: Alle': 'Project: All',
  'Nach Projekt filtern': 'Filter by project',
  'Gruppe': 'Group',
  'Gruppieren nach': 'Group by',
  'Gruppiert nach {by}': 'Grouped by {by}',
  'Nicht gruppiert': 'Not grouped',
  'Sortierung': 'Sort',
  'Sortieren nach': 'Sort by',
  '{time} geschätzt': '{time} estimated',
  '{title} erledigt': '{title} done',
  'Teilaufgaben': 'Subtasks',
  'Teilaufgabe hinzufügen': 'Add subtask',
  'Teilaufgaben erledigt': 'Subtasks done',
  'Keine Aufgaben.': 'No tasks.',
  'Keine offenen Aufgaben.': 'No open tasks.',
  'Keine offenen Aufgaben für heute.': 'No open tasks for today.',
  'Keine offene Aufgabe für heute.': 'No open task for today.',
  'Ressourcen': 'Resources',
  'URL oder Pfad (~ erlaubt)': 'URL or path (~ allowed)',
  'In VSCodium': 'In VSCodium',
  'In VSCodium öffnen': 'Open in VSCodium',
  'VSCodium ↗': 'VSCodium ↗',
  '→ Heute': '→ Today',
  '→ Morgen': '→ Tomorrow',
  '„{title}“ gelöscht': '“{title}” deleted',
  '„{title}“ erledigt': '“{title}” done',
  '„{title}“ abgebrochen': '“{title}” cancelled',
  '„{title}“ geplant': '“{title}” scheduled',
  '„{title}“ eingeplant': '“{title}” scheduled',
  '„{title}“ verschoben': '“{title}” moved',
  '„{title}“ angepasst': '“{title}” resized',
  '„{title}“ auf morgen verschoben': '“{title}” moved to tomorrow',

  // Start
  'Als Nächstes': 'Up next',
  'Heute fällig': 'Due today',
  'Aktiv, nicht für heute geplant': 'Active, not planned for today',
  'Tagesplan': 'Day plan',
  'Es läuft gerade nichts.': 'Nothing is running.',
  'Kein Timer': 'No timer',
  'Ziel': 'Goal',
  'Alle ansehen': 'View all',
  'Zeiterfassung': 'Time tracking',
  'Zeit nachtragen': 'Add time',
  'Eintragen': 'Log',
  'Einplanen': 'Schedule',
  'Projektzeit': 'Project time',
  'Zeit': 'Time',
  'Zeiteintrag gelöscht': 'Time entry deleted',
  'Zeiteintrag löschen?': 'Delete time entry?',
  'Noch keine Zeit erfasst.': 'No time tracked yet.',
  'Keine Zeit erfasst.': 'No time tracked.',
  'Starte eine Aufgabe, um Zeit zu erfassen.': 'Start a task to track time.',
  'erfasst': 'tracked',
  'Erfasst': 'Tracked',
  'frei': 'free',
  'Frei ab jetzt': 'Free from now',
  'Kalenderzeit': 'Calendar time',
  'Kommt noch': 'Coming up',
  'geplant {time}': 'planned {time}',
  '{time} geplant': '{time} planned',
  'Keine Beschreibung': 'No description',
  '{n} erledigt': '{n} done',
  '{n} Aufgabe ohne Schätzung, gerechnet mit 30 Min.': '{n} task without estimate, counted as 30 min.',
  '{n} Aufgaben ohne Schätzung, gerechnet mit 30 Min.': '{n} tasks without estimate, counted as 30 min.',
  'Überplant um {time} h': 'Overplanned by {time} h',
  'Aufgaben aus der Liste in den Plan ziehen, um sie einzuplanen.': 'Drag tasks from the list into the plan to schedule them.',

  // Kalender
  'Termin': 'Event',
  'Termine': 'Events',
  'Neuer Eintrag': 'New entry',
  'Neuer Eintrag (n)': 'New entry (n)',
  'Termin bearbeiten': 'Edit event',
  'Termin löschen': 'Delete event',
  'Termin löschen?': 'Delete event?',
  'Erster Termin': 'First event',
  'Nur dieser Termin': 'Only this event',
  'Nur diesen Termin oder die ganze Serie löschen?': 'Delete only this event or the whole series?',
  'Ganze Serie löschen': 'Delete whole series',
  'Serie mit eigener Regel ({rule}); sie bleibt unverändert.': 'Series with a custom rule ({rule}); it stays unchanged.',
  'Änderungen gelten für die ganze Serie.': 'Changes apply to the whole series.',
  'Mehrtägiger Termin: Beginn und Ende bleiben unverändert.': 'Multi-day event: start and end stay unchanged.',
  'Wöchentlich wiederholen': 'Repeat weekly',
  'Wochentage': 'Weekdays',
  'Endet am': 'Ends on',
  'Kein Projekt': 'No project',
  'ICS importieren': 'Import ICS',
  'Ungeplant': 'Unplanned',
  'in den Plan ziehen': 'drag into the plan',
  'Plan': 'Plan',
  'Ist': 'Act',
  'Plan und Ist pro Tag': 'Plan and actual per day',
  '{n} neu': '{n} new',
  '{n} aktualisiert': '{n} updated',
  '{n} übersprungen': '{n} skipped',
  '{n} Serien als Einzeltermin': '{n} series as single events',

  // Gewohnheiten
  'Gewohnheit': 'Habit',
  'Neue Gewohnheit': 'New habit',
  'Gewohnheiten durchsuchen': 'Search habits',
  'Keine Gewohnheiten.': 'No habits.',
  'Keine aktiven Gewohnheiten.': 'No active habits.',
  'Keine aktive Gewohnheit.': 'No active habit.',
  'Rhythmus': 'Frequency',
  'Täglich': 'Daily',
  'Wöchentlich': 'Weekly',
  'Bestimmte Wochentage': 'Specific weekdays',
  'X-mal pro Woche': 'X times per week',
  'Pro Woche': 'Per week',
  'Wochentag': 'Weekday',
  'Startdatum': 'start date',
  'Serie': 'Streak',
  '· inaktiv': '· inactive',
  'heute nicht fällig': 'not due today',
  '{n}× pro Woche': '{n}× per week',
  '{n} Tage Serie': '{n}-day streak',
  'Letzte 28 Tage: {n} Tage erledigt': 'Last 28 days: {n} days done',
  'Klick auf ein Feld trägt nach oder nimmt zurück': 'Click a cell to log or undo',
  '{active} aktiv · heute {done} von {due} erledigt': '{active} active · {done} of {due} done today',

  // Projekte
  'Neues Projekt': 'New project',
  'Projekt bearbeiten': 'Edit project',
  'Projektname': 'Project name',
  'Projekte durchsuchen': 'Search projects',
  'Keine Projekte.': 'No projects.',
  'Keine Projekte in „{tab}“.': 'No projects in “{tab}”.',
  'Keine Projekte für „{q}“ in „{tab}“.': 'No projects for “{q}” in “{tab}”.',
  'Zuletzt aktiv': 'Last active',
  'Zeit pro Projekt': 'Time per project',
  'Fortschritt und verknüpfte Ressourcen.': 'Progress and linked resources.',
  'Absoluter Pfad oder ~/…, muss existieren (optional)': 'Absolute path or ~/…, must exist (optional)',
  'Erfasst: {week} diese Woche · {total} gesamt': 'Tracked: {week} this week · {total} total',
  '{n} Aufgaben erledigt': '{n} tasks done',
  '„{name}“ löschen? Die Tasks bleiben ohne Projekt, ihre Zeiteinträge landen in „Sonstiges“.': 'Delete “{name}”? Its tasks stay without a project, their time entries move to “Other”.',
  'Violett': 'Violet', 'Blau': 'Blue', 'Orange': 'Orange', 'Türkis': 'Turquoise',
  'Rosa': 'Pink', 'Gelb': 'Yellow', 'Grün': 'Green', 'Rot': 'Red',

  // Rückblick
  'Rückblick': 'Review',
  'Nichts erledigt.': 'Nothing done.',
  'Nichts überfällig.': 'Nothing overdue.',
  '{pct} % von {plan} bis heute geplant': '{pct} % of {plan} planned up to today',
  'erfasst {tracked} h, geplant {plan} h, {done} erledigt': 'tracked {tracked} h, planned {plan} h, {done} done',

  // Papierkorb
  'Papierkorb durchsuchen': 'Search trash',
  'Der Papierkorb ist leer.': 'The trash is empty.',
  '{n} Eintrag': '{n} entry',
  '{n} Einträge': '{n} entries',
  'Keine Treffer für „{q}“.': 'No results for “{q}”.',
  '„{title}“ endgültig löschen? Das lässt sich nicht rückgängig machen.': 'Delete “{title}” permanently? This cannot be undone.',

  // Notizen
  'Neue Notiz': 'New note',
  'Neuer Ordner': 'New folder',
  'Neue Notiz in {name}': 'New note in {name}',
  'Neuer Ordner in {name}': 'New folder in {name}',
  '{name} löschen': 'Delete {name}',
  'Umbenennen (F2)': 'Rename (F2)',
  'Ordnername': 'Folder name',
  'Name der Notiz': 'Note name',
  'Name der neuen Notiz': 'Name of the new note',
  'Name des neuen Ordners': 'Name of the new folder',
  'Datei hinzufügen': 'Add file',
  'PDF, Bild oder Notiz hinzufügen': 'Add PDF, image or note',
  'Vorlage': 'Template',
  'Ungespeichert': 'Unsaved',
  'Ungespeicherte Änderungen verwerfen?': 'Discard unsaved changes?',
  'Kein PDF geöffnet': 'No PDF open',
  'Keine Notiz geöffnet': 'No note open',
  'Geteilte Ansicht': 'Split view',
  'Nur eine Datei zeigen': 'Show one file only',
  'Geteilt: PDF links, Notiz rechts': 'Split: PDF left, note right',
  'Breite der Hälften': 'Width of the halves',
  'Wähle links eine Notiz oder lege eine neue an.': 'Pick a note on the left or create a new one.',
  'Wähle im Baum ein PDF oder ein Bild.': 'Pick a PDF or an image in the tree.',
  'Noch keine Notizen. Lege oben eine an oder zieh PDFs und Bilder hierher.': 'No notes yet. Create one above or drop PDFs and images here.',
  'Datei extern geändert': 'File changed externally',
  'Datei wurde extern geändert': 'File was changed externally',
  'Die Datei wurde außerhalb von Kairo geändert. Beim Speichern fragt Kairo nach.': 'The file was changed outside Kairo. Kairo will ask when you save.',
  'Überschreiben': 'Overwrite',
  'Verwerfen und neu laden': 'Discard and reload',
  'Ein Name darf kein „/“ enthalten und nicht mit „.“ beginnen.': 'A name must not contain “/” or start with “.”.',
  'Eine Datei mit diesem Namen gibt es dort schon.': 'A file with this name already exists there.',
  '„{name}“ existiert schon.': '“{name}” already exists.',
  '„{name}“: Kairo nimmt nur Markdown, PDFs und Bilder (png, jpg, gif, webp).': '“{name}”: Kairo only accepts Markdown, PDFs and images (png, jpg, gif, webp).',
  '„{name}“ löschen? Die Notiz landet in .trash im Notizordner.': 'Delete “{name}”? The note moves to .trash in the notes folder.',
  'Ordner „{name}“ mit allem Inhalt löschen? Er landet in .trash im Notizordner.': 'Delete folder “{name}” with all its contents? It moves to .trash in the notes folder.',
  '„{name}“ wurde seit dem Laden außerhalb von Kairo geändert, zum Beispiel in VSCodium. Überschreiben ersetzt diese Änderungen durch deinen Stand aus Kairo.': '“{name}” was changed outside Kairo since it was loaded, for example in VSCodium. Overwrite replaces those changes with your version from Kairo.',

  // PDF und Bilder bezeichnen
  'Auswählen': 'Select',
  'Stift': 'Pen',
  'Textmarker': 'Highlighter',
  'Linie': 'Line',
  'Pfeil': 'Arrow',
  'Rechteck': 'Rectangle',
  'Ellipse': 'Ellipse',
  'Text': 'Text',
  'Schwarz': 'Black',
  'Weiß': 'White',
  'Dünn': 'Thin',
  'Dick': 'Thick',
  'Auswahl löschen': 'Delete selection',
  'Größe': 'Size',
  'Größe beim Speichern': 'Size when saving',
  'Beim Speichern: {w} × {h} px': 'When saving: {w} × {h} px',
  'Einpassen': 'Fit',
  'Einpassen (⌘0)': 'Fit (⌘0)',
  'Verkleinern': 'Zoom out',
  'Verkleinern (⌘−)': 'Zoom out (⌘−)',
  'Vergrößern': 'Zoom in',
  'Vergrößern (⌘+)': 'Zoom in (⌘+)',
  'Im PDF-Viewer des Browsers öffnen': 'Open in the browser’s PDF viewer',
  'Im PDF-Viewer öffnen (Suche, Drucken)': 'Open in PDF viewer (search, print)',
  'Die Datei lässt sich nicht anzeigen ({reason}).': 'The file cannot be displayed ({reason}).',
  'Dieser Browser kann {type} nicht schreiben.': 'This browser cannot write {type}.',
  'Kairo kann diese PDF nicht bearbeiten (verschlüsselt oder beschädigt).': 'Kairo cannot edit this PDF (encrypted or damaged).',

  // Einstellungen
  'Sprache': 'Language',
  'Gilt sofort, nur in diesem Browser.': 'Applies right away, only in this browser.',
  'Gespeichert in': 'Stored in',
  '. Änderungen gelten nach einem Neustart.': '. Changes apply after a restart.',
  'Notizordner': 'Notes folder',
  'Absoluter Pfad oder ~/…, muss existieren': 'Absolute path or ~/…, must exist',
  'Festgelegt durch': 'Set by',
  'Arbeitszeit von': 'Working hours from',
  'Zeitzone': 'Time zone',
  'Systemzeitzone': 'System time zone',
  'Jetzt neu starten': 'Restart now',
  'Startet neu …': 'Restarting …',
  'Gespeichert. Die neuen Werte gelten nach dem Neustart.': 'Saved. The new values apply after the restart.',
  'Das Backend ist nach dem Neustart nicht erreichbar.': 'The backend is not reachable after the restart.',
}

export default en
